// <auto-generated />
using System;
using Lab1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab1.Migrations
{
    [DbContext(typeof(CacheContext))]
    [Migration("20201030071937_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("Lab1.Cache", b =>
                {
                    b.Property<string>("CacheId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CachedTime")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .HasMaxLength(40960)
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("TEXT");

                    b.HasKey("CacheId");

                    b.ToTable("Caches");
                });
#pragma warning restore 612, 618
        }
    }
}
